version: 2.1

jobs:
  npm_publish_job:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: "依存モジュールをインストールする"
          command: npm install
      - run:
          name: "パッケージをビルドする"
          command: npm run build
      - run: # (d1)
          name: "npmトークンを設定する"
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: # (d2)
          name: "npmパッケージとして公開する"
          command: npm publish

workflows:
  version: 2
  npm_publish:
    jobs:
      - npm_publish_job:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
